allowed_domains:
  - redwoodtoxicology.com
  - cancer.org
  - ahajournals.org
  - rheumatology.org
  - ajnr.org
  - redcross.org
  - ashpublications.org
  - site.thoracic.org
  - auth.gr
  - aruplab.com
  - bdbiosciences.com
  - becarispublishing.com
  - bio-techne.com
  - blueprintgenetics.com
  - bridgespan.org
  - bvhealthsystem.org
  - cardionavigator.com
  - cdisc.org
  - cedars-sinai.org
  - cdc.gov
  - clevelandclinic.org
  - clinicalepigeneticsjournal.biomedcentral.com
  - clinicaltrials.gov
  - cms.gov
  - aapc.com
  - computationalpathologygroup.eu
  - dermnetnz.org
  - elitecardiovascular.com
  - oml.eular.org
  - eurofins.com
  - ppd.com
  - facit.org
  - fulgentgenetics.com
  - health.harvard.edu
  - hcahealthcare.com
  - hologic.com
  - cancer.iu.edu
  - coas.iqvia.com
  - qualitymetric.com
  - jamanetwork.com
  - jnm.snmjournals.org
  - healthy.kaiserpermanente.org
  - kdqol-complete.org
  - labcorp.com
  - lawrencegeneral.org
  - loinc.org
  - eprovide.mapi-trust.org
  - massgeneral.org
  - mayoclinic.org
  - mms.mckesson.com
  - mdanderson.org
  - emedicine.medscape.com
  - mskcc.org
  - mda.gesis.org
  - mountsinai.org
  - nature.com
  - neogenomics.com
  - nhs.uk
  - ncbi.nlm.nih.gov
  - academic.oup.com
  - pearsonclinical.com.au
  - journals.plos.org
  - pockethealth.com
  - hmpglobalevents.com
  - cyto.purdue.edu
  - rbm.q2labsolutions.com
  - questdiagnostics.com
  - rand.org
  - researchgate.net
  - rch.org.au
  - scielo.br
  - sciencedirect.com
  - sralab.org
  - snomed.org
  - sjra.com
  - link.springer.com
  - stanfordlab.com
  - thermofisher.com
  - research.jefferson.edu
  - testmenu.com
  - unityhealth.to
  - uchicago.edu
  - umich.edu
  - ou.edu
  - usf.edu
  - dlmp.uw.edu
  - uwcorr.washington.edu
  - upenn.edu
  - fda.gov
  - medlineplus.gov
  - hhs.gov
  - nursing.vanderbilt.edu
  - verywellhealth.com
  - wpspublish.com
  - onlinelibrary.wiley.com
  - who.int
